version: 2
updates:
  - package-ecosystem: "npm" # npm / yarn / pnpm 중 실제 사용하는 패키지 매니저
    directory: "/"           # package.json이 있는 위치
    schedule:
      interval: "weekly"     # 매주 업데이트 확인
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
